export const plans = [
  {
    name: 'Free',
    type: 'free',
    price: { monthly: 'Grátis', yearly: 'Grátis' },
    priceDetail: 'para sempre',
    color: '#6b7280',
    features: [
      '1 simulação a cada 2 dias',
      'Feedback com IA',
      'Acesso ao dashboard',
      'Histórico de treinos',
    ],
    cta: 'Plano atual',
    highlight: false,
  },
  {
    name: 'Practice',
    type: { monthly: 'practice_monthly', yearly: 'practice_yearly' },
    price: { monthly: 'R$29', yearly: 'R$290' },
    priceDetail: { monthly: 'por mês', yearly: 'por ano · economia de R$58' },
    color: '#1d4ed8',
    features: [
      '1 simulação por dia inclusa',
      'Simulações ilimitadas com API key própria',
      'Feedback detalhado com IA',
      'Histórico completo',
      'Todas as áreas profissionais',
    ],
    cta: 'Assinar Practice',
    highlight: false,
  },
  {
    name: 'Fluent',
    type: { monthly: 'fluent_monthly', yearly: 'fluent_yearly' },
    price: { monthly: 'R$99', yearly: 'R$990' },
    priceDetail: { monthly: 'por mês', yearly: 'por ano · economia de R$198' },
    color: '#059669',
    features: [
      '3 simulações por dia inclusas',
      'Simulações ilimitadas com API key própria',
      'Feedback detalhado com IA',
      'Histórico completo',
      'Todas as áreas profissionais',
      'Suporte prioritário',
    ],
    cta: 'Assinar Fluent',
    highlight: true,
  },
];
